language: minimal
services:
  - docker
script:
  - docker build --no-cache --pull --build-arg VERSION=$TRAVIS_BUILD_NUMBER -t quay.io/wisvch/connect:$TRAVIS_BUILD_NUMBER .
deploy:
  provider: script
  script: >-
    sh -c '
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/wisvch/connect:$TRAVIS_BUILD_NUMBER;
    '
  on:
    branch: master
notifications:
  email: false
  slack:
    secure: Ec1kPzRhZ9RSwqLs6Dt8s3Z5TPQFmRG0Xioxc8TkYwarIhfTsCYB1I5SsNHa4XnCATK3bL3jPaKkhL3kziZrw4VJg8BvkG+8jWUMaVbjcJKgd04P3oKUpsE49Wx7biIAJsJfUCdbuQLyrcHLmdB3GlcNw4nkvR7oSgEIlfvxjV135M310d9kDgC68v37hDOKQVuYK4zaFxKs4QhrIKFRFMugS46LV3m82ZJwxaTuDcWQHKWNQQE8v6zSdLUGzljJyZUAe6w/Txyp3MkjtF0SwRotYpbykU8bBdoAlQ3t+lWUt7N56/TB5+w3dSIm3PChrr23xY1jkzIGLbI+7PUJCE4yq3R7nGfx8aXPSYocw3XDzSrkWhz2ohuMdUoKDYyZ8tzF0Iiblc9KBtWe8rop1C5q1PHMcXOiI+gS0fMbja0joIudrBhyRofmBgwXNrBMNeyghx8pgN1tzDrVjidukz9aZJI4+dmFul6rjNJgggMk7GAUir/ZKeHV08AbCesp3z9ZY5O3VQpBjthPvzx5+pNJUfatncAoVUNKySUKKdJbjtzlt0EZOtA/QFFWi4F+C47UafLoVSNhHaWWVMI1raJQkzppekQn2/mKc+zBvpFxhUVlaY9mGdCJh5WRbjujmYvN7pUlLBJjrnvKdy6H7iKxMWebYgwv7Q+8iFvelus=
