name: Docker
on:
  workflow_dispatch:
  push:
jobs:
  buildDockerImage:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Push to Quay
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: quay.io
        repository: wisvch/connect
        tag_with_ref: true
        tag_with_sha: true
        add_git_labels: true
        push: ${{ github.ref == 'refs/heads/master' }}
